# Generated by Django 3.1.1 on 2020-09-14 22:32

from django.db import migrations
import django_enumfield.db.fields
import network.models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_type',
            field=django_enumfield.db.fields.EnumField(default=0, enum=network.models.ArticleType),
        ),
    ]
