# Generated by Django 3.1.1 on 2020-09-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20200914_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='published_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
