# Generated by Django 3.1.1 on 2020-10-04 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='hero_img',
            field=models.ImageField(blank=True, null=True, upload_to='art/hero/series/'),
        ),
    ]
