# Generated by Django 3.1.1 on 2020-10-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_series_hero_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': 'Series', 'verbose_name_plural': 'Series'},
        ),
        migrations.AddField(
            model_name='article',
            name='hero_img',
            field=models.ImageField(blank=True, null=True, upload_to='art/hero/articles'),
        ),
        migrations.AddField(
            model_name='series',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
