# Generated by Django 3.1.1 on 2020-10-06 22:19

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_auto_20201006_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='logline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
