# Generated by Django 3.1.2 on 2020-10-30 20:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_contactrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactrequest',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='replied',
            field=models.BooleanField(default=False),
        ),
    ]
