# Generated by Django 3.1.1 on 2020-09-11 00:38
import django.contrib.postgres.fields
import django.db.models.deletion
import django_enumfield.db.fields
from django.db import migrations, models

import cards.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('card_type', django_enumfield.db.fields.EnumField(enum=cards.models.CardType)),
                ('color', django_enumfield.db.fields.EnumField(enum=cards.models.CardColor)),
                ('play_cost', models.IntegerField(default=0)),
                ('digivolve_cost', models.IntegerField(blank=True, null=True)),
                ('digivolve_source_color', django.contrib.postgres.fields.ArrayField(base_field=django_enumfield.db.fields.EnumField(enum=cards.models.CardColor), blank=True, null=True, size=None)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('stage', django_enumfield.db.fields.EnumField(default=0, enum=cards.models.DigimonStage)),
                ('digimon_power', models.IntegerField(blank=True, null=True)),
                ('flavor_type', models.CharField(blank=True, max_length=255, null=True)),
                ('flavor_attribute', models.CharField(blank=True, max_length=255, null=True)),
                ('rarity', django_enumfield.db.fields.EnumField(enum=cards.models.CardRarity)),
            ],
        ),
        migrations.CreateModel(
            name='CardEffects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_type', django_enumfield.db.fields.EnumField(enum=cards.models.EffectType)),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('card_types', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CardArt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=255)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.card')),
                ('release_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.releaseset')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='release_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.releaseset'),
        ),
    ]
