# Generated by Django 3.1.1 on 2020-09-11 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20200911_0141'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CardEffects',
            new_name='CardEffect',
        ),
    ]
