# Generated by Django 3.1.1 on 2020-09-13 02:57

import cards.models
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20200911_0218'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('reminder_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DivivolveCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', django_enumfield.db.fields.EnumField(enum=cards.models.CardColor)),
                ('cost', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='card',
            name='digivolve_cost',
        ),
        migrations.RemoveField(
            model_name='card',
            name='digivolve_source_color',
        ),
        migrations.AddField(
            model_name='cardeffect',
            name='card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cards.card'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardeffect',
            name='effect_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardeffect',
            name='card_keyword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cards.cardkeyword'),
        ),
        migrations.AddConstraint(
            model_name='cardeffect',
            constraint=models.CheckConstraint(check=models.Q(('effect_text__isnull', False), ('card_keyword__isnull', False), _connector='OR'), name='effect_or_keyword_needed'),
        ),
        migrations.AddField(
            model_name='divivolvecost',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.card'),
        ),
    ]
