# Generated by Django 3.1.1 on 2020-09-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20200913_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='releaseset',
            name='code',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
