# Generated by Django 3.1.1 on 2020-09-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_auto_20200913_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardart',
            name='card_art',
            field=models.ImageField(default='art/no-img.jpg', upload_to='art/card/'),
        ),
    ]
