# Generated by Django 3.1.1 on 2020-09-14 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_auto_20200914_1802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='releaseset',
            options={'ordering': ['-release_date']},
        ),
    ]
