# Generated by Django 3.1.1 on 2020-09-15 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_auto_20200914_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardart',
            name='card_art',
            field=models.ImageField(default='art/no-img.png', upload_to='art/card/'),
        ),
        migrations.AlterField(
            model_name='releaseset',
            name='set_art',
            field=models.ImageField(default='art/no-img.png', upload_to='art/set/'),
        ),
    ]
