# Generated by Django 3.1.1 on 2020-09-30 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_auto_20200914_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_of_the_day',
            field=models.DateField(blank=True, null=True, unique=True),
        ),
    ]
