# Generated by Django 3.1.2 on 2020-10-12 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_card_card_of_the_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardart',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art', to='cards.card'),
        ),
    ]
