# Generated by Django 3.1.2 on 2020-10-21 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_auto_20201012_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardeffect',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effect', to='cards.card'),
        ),
        migrations.AlterField(
            model_name='divivolvecost',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evo', to='cards.card'),
        ),
    ]
