# Generated by Django 3.1.2 on 2020-10-21 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_auto_20201021_2003'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DivivolveCost',
            new_name='DigivolveCost',
        ),
    ]
