# Generated by Django 3.1.2 on 2020-10-22 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0014_auto_20201021_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardeffect',
            name='card_keyword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='keyword', to='cards.cardkeyword'),
        ),
    ]
